## Numpy Arrays - vectors(1d) and matrices (2d)

In [2]:
import numpy as np

In [2]:
my_list = [1,2,3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,10)       #np.arange(start,stop,step)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
np.random.rand()       # random number between 0 and 1

0.4974917729651247

In [14]:
ranarr = np.random.randint(0,50,10)

In [15]:
ranarr

array([29, 39, 18,  8, 23,  8, 42, 36,  5, 37])

In [16]:
arr.reshape(5,5)

ValueError: cannot reshape array of size 3 into shape (5,5)

In [18]:
ranarr.max()

42

In [20]:
ranarr.argmax()                # index value in the array

6

In [24]:
arr.shape          # shape of that vector 

(3,)

In [25]:
arr.dtype

dtype('int32')

In [26]:
from numpy.random import randint  #calling randint directly 

In [27]:
randint(2,10)

5

In [28]:
import numpy as np

In [31]:
arr = np.arange (0,11)

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
arr[7:]

array([ 7,  8,  9, 10])

In [36]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [37]:
#numpy arrays are able to broadcast 

In [38]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [39]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [41]:
arr_2d[2,2]

45

In [42]:
arr_2d[:2,1:]               # arr_2d[row,column]

array([[10, 15],
       [25, 30]])

In [44]:
arr_2d[1:3,0:]

array([[20, 25, 30],
       [35, 40, 45]])

In [3]:
arr_3 = np.arange(1,11)

In [4]:
arr_3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
bool_array = arr_3>5

In [11]:
arr_3[bool_array]        # conditionally selecting instances in array

array([ 6,  7,  8,  9, 10])

In [24]:
new = np.arange(50).reshape(5,10)                #reshape[Number of rows, number of coulmns]

In [13]:
new

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [14]:
new[1:3,3:5]

array([[13, 14],
       [23, 24]])

## Numpy Operations

In [15]:
import numpy as np

In [16]:
ar = np.arange(0,11)

In [17]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
ar + ar   # array with array operations

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [21]:
ar + 10   # array with scalar operations

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [22]:
np.exp(ar)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])